### ISSUE TITLE
merge with tidyRSS?

### ISSUE THREAD

**Issue by RobertMyles** [jsonbecker/jsonfeedr#1]
Hi,
We were just about to include JSON feeds in the tidyRSS package (see [here](https://github.com/RobertMyles/tidyRSS/issues/6)), and I was wondering if you were interested in merging the packages?

**Comment by jsonbecker** [comment]
Sure. This was mostly a toy example of things people may want to do with jsonfeeds but I'd be happy to contribute support to tidyRSS instead.

**Comment by RobertMyles** [comment]
Ok, great. I'll add you as a collaborator, feel free to propose what you like (given you already have experience with JSON feeds). That ok with you?

**Comment by jsonbecker** [comment]
Yup. I’ll try and work on it a bit in the next week or so and make it consistent with what’s in the existing RSS side.

**Comment by RobertMyles** [comment]
Ok, great.
